#!/usr/bin/env php
<?php

require "vendor/autoload.php";

use EdmondsCommerce\MagentoModuleVersions\ModuleFactory;

use PHPHtmlParser\Dom;

if ($argc !== 2) {
    echo "mmv <path/to/modules.json>\n";
    exit(1);
}

$modulesJson = $argv[1];

if (file_exists($modulesJson) && is_readable($modulesJson)) {
    $moduleConnectPages = json_decode(file_get_contents($modulesJson));
}
else {
    fwrite(STDERR, "ERROR: File '$modulesJson' must exist and be readable\n");
    exit(1);
}

$dom = new Dom();
$table = new Console_Table();
$table->setHeaders(array('Name', 'Version'));

foreach ($moduleConnectPages as $page => $tag) {
    $module = ModuleFactory::create($dom, $page);
    $version = $module->getLatestVersion();
    $table->addRow(array($tag, $version));
}

echo $table->getTable();